#!/bin/bash

# $Id: mksvnver 70 2009-06-08 15:23:12Z jrenken $

SVNVER=`svnversion | sed -e 's/^[0-9]*://'`
COMPILEDATE=`date '+%F %X %z (%c)'`

echo "#ifndef SVNVERSION_H 
#define SVNVERSION_H

#define SVNVERSION	\"$SVNVER\"
#define SVNDATE \"$COMPILEDATE\" 

#endif
" > svnversion.h

echo Svn-Version: $SVNVER

